#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Judge baseline1 results with a Seed model via Ark's OpenAI-compatible API.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path
from typing import Any


DEFAULT_BASE_URL = "https://ark.cn-beijing.volces.com/api/v3"
DEFAULT_MODEL = "doubao-seed-2-0-lite-260215"
REQUIRED_FIELDS = ("question", "ground_truth_answer", "model_answer", "mem_path")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Judge baseline1 result JSON with a Seed model."
    )
    parser.add_argument(
        "--input_file",
        type=str,
        required=True,
        help="Input JSON file generated by the evaluation script.",
    )
    parser.add_argument(
        "--output_file",
        type=str,
        required=True,
        help="Output JSON file path with judge fields.",
    )
    parser.add_argument(
        "--api_key",
        type=str,
        required=False,
        help="API key for Ark/Doubao. If not provided, reads from ARK_API_KEY environment variable.",
    )
    parser.add_argument(
        "--base_url",
        type=str,
        default=DEFAULT_BASE_URL,
        help=f"Base URL for API. Default: {DEFAULT_BASE_URL}",
    )
    parser.add_argument(
        "--model",
        type=str,
        default=DEFAULT_MODEL,
        help=f"Judge model name. Default: {DEFAULT_MODEL}",
    )
    parser.add_argument(
        "--sleep_seconds",
        type=float,
        default=0.0,
        help="Sleep time after each API call. Default: 0",
    )
    return parser.parse_args()


def load_json_file(file_path: str) -> list[dict[str, Any]]:
    path = Path(file_path)
    if not path.is_file():
        raise FileNotFoundError(f"Input file not found: {path}")

    try:
        with path.open("r", encoding="utf-8") as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        raise ValueError(f"Invalid JSON in input file {path}: {e}") from e

    if not isinstance(data, list):
        raise ValueError(
            f"Input file must be a JSON list at the top level, got {type(data).__name__}."
        )

    validated_records: list[dict[str, Any]] = []
    for index, item in enumerate(data):
        if not isinstance(item, dict):
            raise ValueError(
                f"Record at index {index} must be a JSON object, got {type(item).__name__}."
            )
        validate_record_fields(item, index=index)
        validated_records.append(item)

    return validated_records


def save_json_file(file_path: str, data: list[dict[str, Any]]) -> None:
    path = Path(file_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def validate_record_fields(record: dict[str, Any], index: int | None = None) -> None:
    missing_fields = [field for field in REQUIRED_FIELDS if field not in record]
    if missing_fields:
        location = f" at index {index}" if index is not None else ""
        raise KeyError(
            f"Record{location} is missing required field(s): {', '.join(missing_fields)}"
        )


def build_judge_prompt(question: str, ground_truth_answer: str, model_answer: str) -> str:
    return (
        "You are a strict semantic entailment judge for question answering.\n"
        "You will receive:\n"
        "1. a question\n"
        "2. a ground truth answer\n"
        "3. a model answer\n\n"
        "Your task:\n"
        "Decide whether, under the context of the question, the ground truth answer can be "
        "reasonably, logically, and semantically inferred from the model answer.\n\n"
        "Rules:\n"
        "- Do not rely on exact string match.\n"
        "- Do not penalize different wording if the meaning is the same.\n"
        "- Do not reward longer answers unless they actually entail the ground truth.\n"
        "- If the model answer is vague, irrelevant, contradictory, or does not support the ground truth, return No.\n"
        "- If the model answer semantically entails the ground truth, return Yes.\n"
        "- Output only one word: Yes or No.\n"
        "- Do not output any explanation or extra text.\n\n"
        f"Question: {question.strip()}\n"
        f"Ground truth answer: {ground_truth_answer.strip()}\n"
        f"Model answer: {model_answer.strip()}\n\n"
        "Answer:"
    )


def normalize_judge_result(text: str) -> str:
    cleaned = text.strip()
    if not cleaned:
        return "ERROR"

    normalized = " ".join(cleaned.split())
    lowered = normalized.lower().strip(" .,!?:;\"'")

    if lowered == "yes":
        return "Yes"
    if lowered == "no":
        return "No"

    if len(normalized) <= 16:
        tokens = [
            token.strip(" .,!?:;\"'`()[]{}")
            for token in normalized.split()
            if token.strip(" .,!?:;\"'`()[]{}")
        ]
        if len(tokens) == 1:
            token = tokens[0].lower()
            if token == "yes":
                return "Yes"
            if token == "no":
                return "No"

    return "ERROR"


def create_client(api_key: str, base_url: str = DEFAULT_BASE_URL):
    try:
        from openai import OpenAI
    except ImportError as e:
        raise ImportError(
            "openai package is required. Install it with: pip install openai"
        ) from e

    return OpenAI(
        base_url=base_url,
        api_key=api_key,
    )


def judge_one_sample(
    client: Any,
    model: str,
    record: dict[str, Any],
) -> dict[str, Any]:
    output_record = dict(record)

    status = str(record.get("status", "ok"))
    if status != "ok":
        output_record["judge_result"] = "SKIPPED"
        output_record["is_correct"] = False
        return output_record

    prompt = build_judge_prompt(
        question=str(record["question"]),
        ground_truth_answer=str(record["ground_truth_answer"]),
        model_answer=str(record["model_answer"]),
    )

    try:
        response = client.chat.completions.create(
            model=model,
            temperature=0,
            messages=[
                {
                    "role": "system",
                    "content": "You are a semantic QA judge. Reply with only Yes or No.",
                },
                {"role": "user", "content": prompt},
            ],
        )
        raw_text = response.choices[0].message.content or ""
        judge_result = normalize_judge_result(str(raw_text))

        if judge_result == "ERROR":
            output_record["judge_result"] = "ERROR"
            output_record["is_correct"] = False
            output_record["judge_error"] = f"Unexpected judge output: {raw_text!r}"
            return output_record

        output_record["judge_result"] = judge_result
        output_record["is_correct"] = judge_result == "Yes"
        return output_record

    except Exception as e:
        output_record["judge_result"] = "ERROR"
        output_record["is_correct"] = False
        output_record["judge_error"] = str(e)
        return output_record


def compute_accuracy(records: list[dict[str, Any]]) -> tuple[int, int, float]:
    judged_records = [
        record for record in records if record.get("judge_result") in {"Yes", "No"}
    ]
    correct_records = [
        record for record in judged_records if bool(record.get("is_correct")) is True
    ]

    judged_count = len(judged_records)
    correct_count = len(correct_records)
    accuracy = (correct_count / judged_count) if judged_count > 0 else 0.0
    return judged_count, correct_count, accuracy


def main() -> int:
    args = parse_args()

    # 获取 API Key：优先使用命令行参数，否则从环境变量读取
    api_key = args.api_key or os.getenv("ARK_API_KEY")
    if not api_key:
        print(
            "ERROR: API key is not provided. Use --api_key flag or set ARK_API_KEY environment variable.",
            file=sys.stderr,
        )
        return 1

    try:
        records = load_json_file(args.input_file)
    except (FileNotFoundError, ValueError, KeyError) as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1

    try:
        client = create_client(api_key=api_key, base_url=args.base_url)
    except Exception as e:
        print(f"ERROR: Failed to initialize API client: {e}", file=sys.stderr)
        return 1

    judged_records: list[dict[str, Any]] = []
    total_samples = len(records)

    for index, record in enumerate(records, start=1):
        sample_id = record.get("id", f"index_{index - 1}")
        print(f"[{index}/{total_samples}] Judging sample: {sample_id}")

        judged_record = judge_one_sample(
            client=client,
            model=args.model,
            record=record,
        )
        judged_records.append(judged_record)

        if args.sleep_seconds > 0:
            time.sleep(args.sleep_seconds)

    try:
        save_json_file(args.output_file, judged_records)
    except OSError as e:
        print(f"ERROR: Failed to write output file {args.output_file}: {e}", file=sys.stderr)
        return 1

    judged_count, correct_count, accuracy = compute_accuracy(judged_records)

    print(f"Total samples: {total_samples}")
    print(f"Judged samples: {judged_count}")
    print(f"Correct samples: {correct_count}")
    print(f"Accuracy: {accuracy:.4f}")
    print(f"Saved judged results to: {args.output_file}")
    return 0


if __name__ == "__main__":
    sys.exit(main())

# This script is used to automatically judge baseline1 results.
# The reported accuracy depends on the judge model and is not equal to absolute human annotation.
# For stricter evaluation later, you can sample cases and compare with manual review.
